inherit_from: .rubocop_todo.yml

AllCops: 
  NewCops: enable

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: False

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Lint/MissingSuper:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Security/Eval:
  Enabled: false