default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: api_bot_dev
  host: db
  username: postgres
  password: postgres

test:
  <<: *default
  database: api_bot_test

production:
  <<: *default
  database: api_bot_prod
  username: api_bot_backend
  password: <%= ENV['API_BOT_BACKEND_DATABASE_PASSWORD'] %>
